[workspace]
members = [
  "crates/lib1",
  "crates/shared_types",
  "bindings/wasm", "crates/macros",
]
resolver = "1"

[workspace.dependencies]
anyhow = "1.0.79"
crux_core = "0.7"
serde = "1.0.196"
wasm-bindgen = "0.2.91"
