name = "Tic-Toc-Toe"

# micropip is used to install whl
packages = ["micropip"]

# Configure files to be loaded into the virtual filesystem
[files]
"./tictactoe-0.1.0-cp313-abi3-emscripten_4_0_9_wasm32.whl" = "./tictactoe-0.1.0-cp313-abi3-emscripten_4_0_9_wasm32.whl"
