apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/<docker_username>/helloworld-go
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: TARGET
            value: "Go Sample v1"
