site_name: Tech Journey
site_description: Algorithms and Design Documentation
docs_dir: ..
site_dir: ../../site

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: indigo
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Algorithms:
      - Array: algorithm/array.md
      - Binary Search: algorithm/binary-search.md
      - Dynamic Programming: algorithm/dynamic-programming.md
      - Graph: algorithm/graph.md
      - Greedy: algorithm/greedy.md
      - Hash Table: algorithm/hash-table.md
      - Backtracking: algorithm/backtracking.md
      - Math: algorithm/math.md
      - String: algorithm/string.md
      - Design: algorithm/design.md
      - SQL: algorithm/sql.md
  - SQL: design/sql/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - awesome-pages
