site_name: Tech Journey
site_description: Algorithms and Design Documentation
docs_dir: ..
site_dir: ../../site

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: indigo
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Algorithms:
      - Array: algorithm/array.md
      - Binary Search: algorithm/binary-search.md
      - Dynamic Programming: algorithm/dynamic-programming.md
      - Graph: algorithm/graph.md
      - Greedy: algorithm/greedy.md
      - Hash Table: algorithm/hash-table.md
      - Backtracking: algorithm/backtracking.md
      - Math: algorithm/math.md
      - String: algorithm/string.md
      - Design: algorithm/design.md
      - SQL: algorithm/sql.md
  - SQL: design/sql/
  - Spacedrive: design/spacedrive/
  - Rust:
    - Arrow-Based CSV Data Processing: design/rust/rust_apache_arrow.md
    - Cython CSV Processing: design/rust/rust_csv_cython.md
    - Zero-cost Async: design/rust/rust_zero_cost_async.md
    - Zero Copy: design/rust/rust_zero_copy.md
  - Nautilus Trader:
    - Thread Model: design/nautilus-trader/thread_model.md
    - Crates:
      - Risk: design/nautilus-trader/crates/risk/risk.md
      - Execution:
        - Engine: design/nautilus-trader/crates/execution/engine.md
        - Order Manager: design/nautilus-trader/crates/execution/order_manager.md
        - Matching Engine: design/nautilus-trader/crates/execution/matching_engine.md
        - Matching Core: design/nautilus-trader/crates/execution/matching_core.md
        - Order Emulator: design/nautilus-trader/crates/execution/order_emulator.md
        - Reconciliation: design/nautilus-trader/crates/execution/reconciliation.md
    - Concepts:
      - Trading Chart: design/nautilus-trader/concepts/tradingchart.md
      - Trade Tick: design/nautilus-trader/concepts/trade_tick.md
      - Quote Tick: design/nautilus-trader/concepts/quote_tick.md
      - Order Book: design/nautilus-trader/concepts/order_book.md
      - Fill Model: design/nautilus-trader/concepts/fill_model.md
      - Simulated Exchange: design/nautilus-trader/concepts/simulated_exchange.md
      - Model DDD File: design/nautilus-trader/concepts/model_ddd_file.md
    - Python-Rust FFI Streaming: design/nautilus-trader/python-rust-ffi-streaming.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - awesome-pages
