site_name: Tech Journey
site_description: Algorithms and Design Documentation
docs_dir: ..
site_dir: ../../site

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: indigo
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Algorithms:
      - Array: algorithm/array.md
      - Binary Search: algorithm/binary-search.md
      - Dynamic Programming: algorithm/dynamic-programming.md
      - Graph: algorithm/graph.md
      - Greedy: algorithm/greedy.md
      - Hash Table: algorithm/hash-table.md
      - Backtracking: algorithm/backtracking.md
      - Math: algorithm/math.md
      - String: algorithm/string.md
      - Design: algorithm/design.md
      - SQL: algorithm/sql.md
  - SQL: design/sql/
  - Spacedrive: design/spacedrive/
  - Rust:
    - Arrow-Based CSV Data Processing: design/rust/rust_apache_arrow.md
    - Cython CSV Processing: design/rust/rust_csv_cython.md
    - Zero-cost Async: design/rust/rust_zero_cost_async.md
    - Zero Copy: design/rust/rust_zero_copy.md
  - Nautilus Trader:
    - Thread Model: design/nautilus-trader/thread_model.md
    - Handler Binding: design/nautilus-trader/handler-binding.md
    - Backtest Order Book Replay: design/nautilus-trader/backtest-order-book-replay.md
    - Crates:
      - Risk: design/nautilus-trader/crates/risk/risk.md
      - Execution:
        - Engine: design/nautilus-trader/crates/execution/engine.md
        - Order Manager: design/nautilus-trader/crates/execution/order_manager.md
        - Matching Engine: design/nautilus-trader/crates/execution/matching_engine.md
        - Matching Core: design/nautilus-trader/crates/execution/matching_core.md
        - Matching Engine Split: design/nautilus-trader/crates/execution/matching_engine_split.md
        - Order Emulator: design/nautilus-trader/crates/execution/order_emulator.md
        - Reconciliation: design/nautilus-trader/crates/execution/reconciliation.md
      - Backtest:
        - Introduction: design/nautilus-trader/crates/backtest/backtest.md
        - Engine: design/nautilus-trader/crates/backtest/engine.md
      - Portfolio:
        - Portfolio: design/nautilus-trader/crates/portfolio/portfolio.md
        - Manager: design/nautilus-trader/crates/portfolio/manager.md
      - Data:
        - Engine:
          - Engine: design/nautilus-trader/crates/data/engine/engine.md
    - Concepts:
      - Trading Chart: design/nautilus-trader/concepts/tradingchart.md
      - Trade Tick: design/nautilus-trader/concepts/trade_tick.md
      - Quote Tick: design/nautilus-trader/concepts/quote_tick.md
      - Order Book: design/nautilus-trader/concepts/order_book.md
      - Fill Model: design/nautilus-trader/concepts/fill_model.md
      - Simulated Exchange: design/nautilus-trader/concepts/simulated_exchange.md
      - Model DDD File: design/nautilus-trader/concepts/model_ddd_file.md
      - Position: design/nautilus-trader/concepts/position.md
      - Venue: design/nautilus-trader/concepts/venue.md
      - Instruments:
        - Overview: design/nautilus-trader/concepts/instruments/overview.md
        - Instrument: design/nautilus-trader/concepts/instruments/instrument.md
        - Synthetic Instrument: design/nautilus-trader/concepts/instruments/synthetic_instrument.md
        - Betting Instrument: design/nautilus-trader/concepts/instruments/betting_instrument.md
        - Binary Option: design/nautilus-trader/concepts/instruments/binary_option.md
        - CFD: design/nautilus-trader/concepts/instruments/cfd.md
        - Commodity: design/nautilus-trader/concepts/instruments/commodity.md
        - Crypto Future: design/nautilus-trader/concepts/instruments/crypto_future.md
        - Crypto Perpetual: design/nautilus-trader/concepts/instruments/crypto_perpetual.md
        - Currency Pair: design/nautilus-trader/concepts/instruments/currency_pair.md
        - Equity: design/nautilus-trader/concepts/instruments/equity.md
        - Futures Contract: design/nautilus-trader/concepts/instruments/futures_contract.md
        - Option Contract: design/nautilus-trader/concepts/instruments/option_contract.md
      - Orders:
        - Index: design/nautilus-trader/concepts/orders/index.md
        - Market Order: design/nautilus-trader/concepts/orders/market-order.md
        - Limit Order: design/nautilus-trader/concepts/orders/limit-order.md
        - Stop Market Order: design/nautilus-trader/concepts/orders/stop-market-order.md
        - Stop Limit Order: design/nautilus-trader/concepts/orders/stop-limit-order.md
        - Market If Touched Order: design/nautilus-trader/concepts/orders/market-if-touched-order.md
        - Limit If Touched Order: design/nautilus-trader/concepts/orders/limit-if-touched-order.md
        - Market To Limit Order: design/nautilus-trader/concepts/orders/market-to-limit-order.md
        - Trailing Stop Market Order: design/nautilus-trader/concepts/orders/trailing-stop-market-order.md
        - Trailing Stop Limit Order: design/nautilus-trader/concepts/orders/trailing-stop-limit-order.md
    - Python-Rust FFI Streaming: design/nautilus-trader/python-rust-ffi-streaming.md
    - Py03:
      - call_function: design/nautilus-trader/pyo3/call_python.md
      - call_python_threadsafe: design/nautilus-trader/pyo3/call_python_threadsafe.md
  - Trading-Vue-Js:
      - Candlestick Scaling: design/trading-vue-js/candlestick-scaling.md
      - Chart Event: design/trading-vue-js/chart-event.md
      - Crosshair: design/trading-vue-js/crosshair.md
      - Drawing Timing: design/trading-vue-js/drawing-timing.md
      - Layout: design/trading-vue-js/layout.md
      - Range: design/trading-vue-js/range.md
      - Script: design/trading-vue-js/script.md
      - Zoom Draw: design/trading-vue-js/zoom-draw.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - awesome-pages
