// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc 25.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `auth.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:SignUpPayloadPB)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SignUpPayloadPB {
    // message fields
    // @@protoc_insertion_point(field:SignUpPayloadPB.email)
    pub email: ::std::string::String,
    // @@protoc_insertion_point(field:SignUpPayloadPB.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:SignUpPayloadPB.password)
    pub password: ::std::string::String,
    // @@protoc_insertion_point(field:SignUpPayloadPB.auth_type)
    pub auth_type: ::protobuf::EnumOrUnknown<AuthenticatorPB>,
    // @@protoc_insertion_point(field:SignUpPayloadPB.device_id)
    pub device_id: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:SignUpPayloadPB.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SignUpPayloadPB {
    fn default() -> &'a SignUpPayloadPB {
        <SignUpPayloadPB as ::protobuf::Message>::default_instance()
    }
}

impl SignUpPayloadPB {
    pub fn new() -> SignUpPayloadPB {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "email",
            |m: &SignUpPayloadPB| { &m.email },
            |m: &mut SignUpPayloadPB| { &mut m.email },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &SignUpPayloadPB| { &m.name },
            |m: &mut SignUpPayloadPB| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "password",
            |m: &SignUpPayloadPB| { &m.password },
            |m: &mut SignUpPayloadPB| { &mut m.password },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "auth_type",
            |m: &SignUpPayloadPB| { &m.auth_type },
            |m: &mut SignUpPayloadPB| { &mut m.auth_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_id",
            |m: &SignUpPayloadPB| { &m.device_id },
            |m: &mut SignUpPayloadPB| { &mut m.device_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SignUpPayloadPB>(
            "SignUpPayloadPB",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SignUpPayloadPB {
    const NAME: &'static str = "SignUpPayloadPB";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.email = is.read_string()?;
                },
                18 => {
                    self.name = is.read_string()?;
                },
                26 => {
                    self.password = is.read_string()?;
                },
                32 => {
                    self.auth_type = is.read_enum_or_unknown()?;
                },
                42 => {
                    self.device_id = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.email.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.email);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.password.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.password);
        }
        if self.auth_type != ::protobuf::EnumOrUnknown::new(AuthenticatorPB::Local) {
            my_size += ::protobuf::rt::int32_size(4, self.auth_type.value());
        }
        if !self.device_id.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.device_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.email.is_empty() {
            os.write_string(1, &self.email)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.password.is_empty() {
            os.write_string(3, &self.password)?;
        }
        if self.auth_type != ::protobuf::EnumOrUnknown::new(AuthenticatorPB::Local) {
            os.write_enum(4, ::protobuf::EnumOrUnknown::value(&self.auth_type))?;
        }
        if !self.device_id.is_empty() {
            os.write_string(5, &self.device_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SignUpPayloadPB {
        SignUpPayloadPB::new()
    }

    fn clear(&mut self) {
        self.email.clear();
        self.name.clear();
        self.password.clear();
        self.auth_type = ::protobuf::EnumOrUnknown::new(AuthenticatorPB::Local);
        self.device_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SignUpPayloadPB {
        static instance: SignUpPayloadPB = SignUpPayloadPB {
            email: ::std::string::String::new(),
            name: ::std::string::String::new(),
            password: ::std::string::String::new(),
            auth_type: ::protobuf::EnumOrUnknown::from_i32(0),
            device_id: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SignUpPayloadPB {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SignUpPayloadPB").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SignUpPayloadPB {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SignUpPayloadPB {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:AuthenticatorPB)
pub enum AuthenticatorPB {
    // @@protoc_insertion_point(enum_value:AuthenticatorPB.Local)
    Local = 0,
    // @@protoc_insertion_point(enum_value:AuthenticatorPB.Supabase)
    Supabase = 1,
    // @@protoc_insertion_point(enum_value:AuthenticatorPB.AppFlowyCloud)
    AppFlowyCloud = 2,
}

impl ::protobuf::Enum for AuthenticatorPB {
    const NAME: &'static str = "AuthenticatorPB";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<AuthenticatorPB> {
        match value {
            0 => ::std::option::Option::Some(AuthenticatorPB::Local),
            1 => ::std::option::Option::Some(AuthenticatorPB::Supabase),
            2 => ::std::option::Option::Some(AuthenticatorPB::AppFlowyCloud),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<AuthenticatorPB> {
        match str {
            "Local" => ::std::option::Option::Some(AuthenticatorPB::Local),
            "Supabase" => ::std::option::Option::Some(AuthenticatorPB::Supabase),
            "AppFlowyCloud" => ::std::option::Option::Some(AuthenticatorPB::AppFlowyCloud),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [AuthenticatorPB] = &[
        AuthenticatorPB::Local,
        AuthenticatorPB::Supabase,
        AuthenticatorPB::AppFlowyCloud,
    ];
}

impl ::protobuf::EnumFull for AuthenticatorPB {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("AuthenticatorPB").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for AuthenticatorPB {
    fn default() -> Self {
        AuthenticatorPB::Local
    }
}

impl AuthenticatorPB {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<AuthenticatorPB>("AuthenticatorPB")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\nauth.proto\"\xa3\x01\n\x0fSignUpPayloadPB\x12\x14\n\x05email\x18\x01\
    \x20\x01(\tR\x05email\x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04name\x12\
    \x1a\n\x08password\x18\x03\x20\x01(\tR\x08password\x12-\n\tauth_type\x18\
    \x04\x20\x01(\x0e2\x10.AuthenticatorPBR\x08authType\x12\x1b\n\tdevice_id\
    \x18\x05\x20\x01(\tR\x08deviceId*=\n\x0fAuthenticatorPB\x12\t\n\x05Local\
    \x10\0\x12\x0c\n\x08Supabase\x10\x01\x12\x11\n\rAppFlowyCloud\x10\x02b\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(SignUpPayloadPB::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(AuthenticatorPB::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
