[package]
name = "protobuf-binding"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "3.4.0" }

[build-dependencies]
protobuf-codegen = { version = "3.4.0" }
