const path = require("path");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const WasmPackPlugin = require('@wasm-tool/wasm-pack-plugin')


module.exports = {
    entry: "./js/index",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "index.js",
    },
    mode: "development",
    module: {
        rules: [{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }, {
            test: /\.vue$/,
            use: ['vue-loader'],
        }, {
            test: /\.js$/,
            // This loader is needed because the script generated by wasm-pack uses
            // `import.meta` and webpack craps out on it.
            loader: require.resolve('@open-wc/webpack-import-meta-loader'),
        },{
            test: /\.wasm$/,
            type: "javascript/auto" /** this disables webpacks default handling of wasm */,
            loader: 'file-loader',
        }]
    },
    resolve: {
        extensions: ['.js'],
    },
    plugins: [
        new CopyWebpackPlugin({
            patterns: ["js/index.html"]
        }),
        new VueLoaderPlugin(),
        new WasmPackPlugin({
            crateDirectory: __dirname,
            extraArgs: "--target web",
        })
    ],
    // experiments: {
    //     asyncWebAssembly: true
    // }
}